import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string;

  return (
    <html lang="en">
      <body className={outfit.variable}>
        {googleClientId ? (
          <GoogleOAuthProvider clientId={googleClientId}>
            <Navbar />
            {children}
          </GoogleOAuthProvider>
        ) : (
          <div>Google Client ID is not set. Please check your environment variables.</div>
        )}
      </body>
    </html>
  );
}
